{
  LinearLayout;
  layout_height="fill";
  layout_width="fill";
  orientation="vertical";
  background="#FFEDEDED";
  {
    FrameLayout;
    layout_height="wrap_content";
    layout_width="fill";
    {
      LinearLayout;
      id="toolbar_one";
      layout_height="wrap_content";
      layout_width="fill";
      orientation="vertical";
      {
        LinearLayout;
        layout_height=Status_bar();
      },
      {
        LinearLayout;
        layout_height="48dp";
        layout_width="fill";
        orientation="horizontal";
        {
          TextView;
          id="title";
          text="班费查(20408)";
          textSize="17dp";
          textColor="#FF202020";
          layout_height="fill";
          layout_width="fill";
          layout_weight="1";
          layout_marginLeft="15dp";
          gravity="center|left";
        },
        {
          FrameLayout;
          layout_height="fill";
          layout_width="56dp";
          {
            CardView;
            layout_height="40dp";
            layout_width="40dp";
            layout_gravity="center";
            radius="20dp";
            elevation="0dp";
            CardBackgroundColor="#00000000";
            {
              FrameLayout;
              id="search";
              layout_height="fill";
              layout_width="fill";
              {
                ImageView;
                layout_height="22dp";
                layout_width="22dp";
                layout_gravity="center";
                colorFilter="#ff000000";
                src="Image/icon/search.png";
              }
            }
          }
        },
        {
          FrameLayout;
          layout_height="fill";
          layout_width="56dp";
          {
            CardView;
            layout_height="40dp";
            layout_width="40dp";
            layout_gravity="center";
            radius="20dp";
            elevation="0dp";
            CardBackgroundColor="#00000000";
            {
              FrameLayout;
              id="bfc1";
              layout_height="fill";
              layout_width="fill";
              {
                ImageView;
                layout_height="21dp";
                layout_width="21dp";
                id="Jiang";
                layout_gravity="center";
                colorFilter="#ff000000";
                src="Image/icon/more.png";
              }
            }
          }
        }
      },
    },
    {
      LinearLayout;
      id="toolbar_two";
      Visibility="invisible";
      layout_height="wrap_content";
      layout_width="fill";
      orientation="vertical";
      background="#ffffffff";
      {
        LinearLayout;
        layout_height=Status_bar();
      },
      {
        LinearLayout;
        layout_height="48dp";
        layout_width="fill";
        orientation="horizontal";
        {
          LinearLayout;
          layout_height="fill";
          layout_width="fill";
          layout_weight="1";
        },
        {
          FrameLayout;
          layout_height="fill";
          layout_width="56dp";
          {
            CardView;
            layout_height="40dp";
            layout_width="40dp";
            layout_gravity="center";
            radius="20dp";
            elevation="0dp";
            CardBackgroundColor="#00000000";
            {
              FrameLayout;
              id="photo";
              layout_height="fill";
              layout_width="fill";
              {
                ImageView;
                layout_height="22dp";
                layout_width="22dp";
                layout_gravity="center";
                colorFilter="#ff000000";
                src="Image/icon/custom_photo.png";
              }
            }
          }
        },
      },
    }
  };
  {
    PageView;
    id="page";
    layout_height="fill";
    layout_width="fill";
    layout_weight="1";
    pages={
      "Page/page1",
      "Page/page2",
      "Page/page3",
      "Page/page4"
    }
  },
  {
    LinearLayout;
    layout_height="1";
    layout_width="fill";
    background="#28000000";
  },
  {
    LinearLayout;
    layout_height="56dp";
    layout_width="fill";
    orientation="horizontal";
    background="#FFF7F7F7";
    {
      ImageView;
      id="home";
      layout_height="fill";
      layout_width="fill";
      layout_weight="1";
      layout_gravity="center";
      src="Image/icon/home2.png";
    },
    {
      ImageView;
      id="friend";
      layout_height="fill";
      layout_width="fill";
      layout_weight="1";
      layout_gravity="center";
      src="Image/icon/friend.png";
    },
    {
      ImageView;
      id="discover";
      layout_height="fill";
      layout_width="fill";
      layout_weight="1";
      layout_gravity="center";
      src="Image/icon/discover.png";
    },
    {
      ImageView;
      id="custom";
      layout_height="fill";
      layout_width="fill";
      layout_weight="1";
      layout_gravity="center";
      src="Image/icon/custom.png";
    }
  }
}




