{
  LinearLayout;
  layout_height="56dp";
  layout_width="fill";
  orientation="horizontal";
  background="#FFFFFFFF";
  {
    FrameLayout;
    layout_height="fill";
    layout_width="56dp";
    {
      CardView;
      layout_height="fill";
      layout_width="fill";
      layout_margin="10dp";
      radius="4dp";
      elevation="0dp";
      CardBackgroundColor="#FFDEDFE3";
      {
        ImageView;
        id="friend_icon";
        layout_height="fill";
        layout_width="fill";
        scaleType="fitXY";
      }
    }
  },
  {
    LinearLayout;
    layout_height="fill";
    layout_width="fill";
    layout_weight="1";
    orientation="vertical";
    {
      TextView;
      id="friend_title";
      text="MCBBS_007";
      textSize="16.5dp";
      textColor="#FF373737";
      layout_height="fill";
      layout_width="wrap_content";
      layout_weight="1";
      layout_marginLeft="1dp";
      layout_marginBottom="1dp";
      gravity="center";
    },
    {
      LinearLayout;
      layout_height="1";
      layout_width="fill";
      background="#28000000";
    },
  }
}